# 一个集群 server一般是相同的
[server]
#type = 'redis'
#ip = 'localhost'
#port = 6379
type = 'nats'
ip = 'localhost'
port = 4231
#设备名称和ip输入有一个就可以
#每个网卡一个配置文件
[device]
name = ""
ip = ""
#db 数组，可以配置多个机器
[[db]]
type = 'mysql'
port = 3306
[[db]]
type = 'postgre'
port = 5432
[[db]]
type = 'oracle'
port = 1521
