# 消息队列后端的配置，需要消息队列已启动
[message_server]
# 消息队列类型 目前支持 redis nats
type = 'nats'
# 消息队列的ip or host
ip = 'localhost'
# 消息队列的端口
port = 4222
# 消息队列的队列名称
queue = 'message'

#如果message_server是type = nats 才需要配置
[nats]
#default 如果没有会自动创建，其他没有会报错
stream = "default"